# Generated by Django 3.0.2 on 2020-01-19 01:56

from django.db import migrations, models
import django.utils.timezone
import yoyaku.models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', yoyaku.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.BigIntegerField(default=1, verbose_name='group id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
            preserve_default=False,
        ),
    ]
