# Generated by Django 3.0.2 on 2020-03-05 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0005_auto_20200119_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='association',
            field=models.CharField(default='Success Academy', max_length=200, verbose_name='group association'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ManyToManyField(related_name='subjects', related_query_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
