# Generated by Django 3.0.2 on 2020-03-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0006_auto_20200305_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_grade',
            field=models.IntegerField(choices=[(-1, 'Preschool'), (0, 'Kindergarten'), (1, 'First Grade'), (2, 'Second Grade'), (3, 'Third Grade'), (4, 'Fourth Grade'), (5, 'Fifth Grade'), (6, 'Sixth Grade'), (7, 'Seventh Grade'), (8, 'Eight Grade'), (9, 'Ninth Grade'), (10, 'Tenth Grade'), (11, 'Eleventh Grade'), (12, 'Twelfth Grade')], null=True, verbose_name='school grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(max_length=200, null=True, verbose_name='school name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='association',
            field=models.CharField(max_length=200, null=True, verbose_name='group association'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
