# Generated by Django 3.0.2 on 2020-03-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0008_auto_20200312_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group_id',
        ),
    ]
