# Generated by Django 3.0.2 on 2020-03-28 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0009_remove_event_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(default='Hi, I am a user', max_length=300, verbose_name='personal description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='1112223333', max_length=15, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
