# Generated by Django 3.0.4 on 2020-04-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0010_auto_20200328_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='personal description'),
        ),
    ]
