# Generated by Django 3.0.4 on 2020-04-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0012_auto_20200411_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.CharField(default='hello', max_length=1000, verbose_name='comment'),
            preserve_default=False,
        ),
    ]
