# Generated by Django 3.0.4 on 2020-04-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0014_auto_20200426_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(null=True, upload_to='eventFiles'),
        ),
    ]
