# Generated by Django 3.0.4 on 2020-05-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0015_auto_20200427_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(null=True, upload_to='eventFiles/'),
        ),
    ]
