# Generated by Django 3.0.4 on 2020-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0017_auto_20200525_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='backgroundColor',
            field=models.CharField(default='orange', max_length=10, verbose_name='background color'),
        ),
    ]
