# Generated by Django 3.0.4 on 2020-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0018_event_backgroundcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='backgroundColor',
            field=models.CharField(default='blue', max_length=10, verbose_name='background color'),
        ),
    ]
