# Generated by Django 3.0.7 on 2020-08-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0021_auto_20200705_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stripeCustomerId',
            field=models.CharField(max_length=300, null=True, verbose_name='stripe customer id'),
        ),
    ]
