# Generated by Django 3.0.7 on 2020-08-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0023_auto_20200816_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stripeSubscriptionProvision',
            field=models.BooleanField(default=False),
        ),
    ]
