# Generated by Django 3.0.7 on 2020-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0024_myuser_stripesubscriptionprovision'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='referrer',
            field=models.CharField(default='referrer', max_length=20, verbose_name='referrer'),
            preserve_default=False,
        ),
    ]
