# Generated by Django 3.0.7 on 2020-08-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0025_studentprofile_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='referrer',
            field=models.CharField(blank=True, max_length=20, verbose_name='referrer'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_grade',
            field=models.IntegerField(choices=[(-1, '未就学'), (0, '幼稚園'), (1, '小１'), (2, '小２'), (3, '小３'), (4, '小４'), (5, '小５'), (6, '小６'), (7, '中１'), (8, '中２'), (9, '中３'), (10, '高１'), (11, '高２'), (12, '高３'), (13, '高４')], verbose_name='school grade'),
        ),
    ]
