# Generated by Django 3.0.7 on 2020-10-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0028_auto_20201018_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='should_pay_signup_fee',
            field=models.BooleanField(default=False),
        ),
    ]
