# Generated by Django 3.0.7 on 2021-01-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0030_classinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='access',
            field=models.CharField(choices=[('全員', 'all'), ('土日', 'weekend'), ('未就学児', 'preschool')], default='全員', max_length=20, verbose_name='access'),
            preserve_default=False,
        ),
    ]
