# Generated by Django 3.0.7 on 2021-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0031_classinfo_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='access',
            field=models.CharField(choices=[('all', 'all'), ('weekend', 'weekend'), ('preschool', 'preschool')], max_length=20, verbose_name='access'),
        ),
    ]
