# Generated by Django 3.0.7 on 2021-02-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0033_auto_20210215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='yoyaku.PreschoolClass'),
        ),
    ]
