# Generated by Django 3.0.7 on 2021-03-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku', '0034_auto_20210228_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschoolclass',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='preschool class comment'),
        ),
    ]
